"""add is deleted

Revision ID: 6f5ff6e693fd
Revises: 46cae3f3c7ac
Create Date: 2023-11-10 16:55:47.672621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5ff6e693fd'
down_revision: Union[str, None] = '46cae3f3c7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['nick_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'deleted')
    op.drop_column('pricing', 'deleted')
    # ### end Alembic commands ###
